language: php
php:
- '5.6'
- '7.0'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /v?\d+\.\d+\.\d+/


before_script:
  - composer install
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - php -d phar.readonly=0 ./box.phar build

script:
  - ./wp-deploy.phar --help
